// src/pages/DailyReport/mockDailyReportData.js

export const MOCK_METRICS = {
  totalProjects: 14,
  notStartedTasks: 11,
  inProgressTasks: 28,
  lastCompleted: 19,
  totalCompleted: 45,
};

export const MOCK_GLOBAL_TABS = [
  { key: 'All', label: 'All', count: 52 },
  { key: 'In Progress', label: 'In Progress', count: 44 },
  { key: 'On Hold', label: 'On Hold', count: 19 },
  { key: 'Completed', label: 'Completed', count: 19 },
];

export const MOCK_PROJECTS = [
  {
    id: 'PRJ-9021',
    name: 'FMS',
    projectCode: 'ID #PRJ-9021',
    statusTag: 'On Schedule',
    lead: 'Kusum',
    teamMembersCount: 4,
    timeline: '01 Aug 2024 → 30 Sep 2024',
    activeTasksCount: 5,
    milestoneCompletion: 78,
    tabCounts: {
      all: 103,
      inProgress: 11,
      lastCompleted: 19,
      totalCompleted: 45,
      notStarted: 28,
      blockers: 4,
      delayed: 3,
      dueToday: 8,
    },
    tasks: [
      {
        id: 'fms-1',
        classification: 'IN-PROGRESS',
        taskCode: 'T-1024',
        taskName: 'RBAC Permission Matrix & API Endpoints',
        ownerName: 'Navithkumar V.',
        role: 'Fullstack',
        ownerRole: 'Fullstack',
        taskType: 'Development',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Awaiting: InfoSec team formal sign-off for OAuth scoping.',
        remarksPrefix: 'Awaiting:',
        remarksPrefixColor: '#D97706',
        plannedStart: '18 Aug 2024',
        plannedEnd: '22 Aug 2024',
        actualLine1: '11 Aug →',
        actualLine2: 'Running',
        varianceBadge: {
          label: 'On track',
          type: 'neutral',
        },
        status: 'In Progress',
        progressPct: 65,
        globalTab: 'In Progress',
      },
      {
        id: 'fms-2',
        classification: 'IN-PROGRESS',
        taskCode: 'T-1025',
        taskName: '1366px Responsive Grid & Task Matrix UI',
        ownerName: 'Bedasur V.',
        role: 'UI/UX',
        ownerRole: 'UI/UX',
        taskType: 'Design',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Blocker: Horizontal scroll glitch on nested tables in Firefox ESR; patch in testing.',
        remarksPrefix: 'Blocker:',
        remarksPrefixColor: '#DC2626',
        plannedStart: '13 Aug 2024',
        plannedEnd: '24 Aug 2024',
        actualLine1: '14 Aug →',
        actualLine2: 'Running',
        varianceBadge: {
          label: '+1d start lag',
          type: 'warning',
          icon: '⚡',
        },
        status: 'In Progress',
        progressPct: 48,
        globalTab: 'In Progress',
        isDelayed: true,
        isBlocker: true,
      },
      {
        id: 'fms-3',
        classification: 'LAST COMPLETED',
        taskCode: 'T-1020',
        taskName: 'Core Authentication & JWT Middleware',
        ownerName: 'Navithkumar V.',
        role: 'Backend',
        ownerRole: 'Backend',
        taskType: 'Architecture',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Merged to staging branch. Code reviewed by Yusuf.',
        plannedStart: '01 Aug 2024',
        plannedEnd: '06 Aug 2024',
        actualLine1: '01 Aug → 07',
        actualLine2: 'Aug',
        varianceBadge: {
          label: '1 day early',
          type: 'success',
          icon: '⚡',
        },
        status: 'Completed',
        progressPct: 100,
        globalTab: 'Completed',
      },
      {
        id: 'fms-4',
        classification: 'LAST COMPLETED',
        taskCode: 'T-1021',
        taskName: 'PostgreSQL Schema Partitioning & Indexing',
        ownerName: 'Yusuf Mohammed',
        role: 'Data Eng',
        ownerRole: 'Data Eng',
        taskType: 'Development',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Query latency reduced by 40% on historical reports.',
        plannedStart: '02 Aug 2024',
        plannedEnd: '10 Aug 2024',
        actualLine1: '02 Aug → 09',
        actualLine2: 'Aug',
        varianceBadge: {
          label: '1 day early',
          type: 'success',
          icon: '⚡',
        },
        status: 'Completed',
        progressPct: 100,
        globalTab: 'Completed',
      },
      {
        id: 'fms-5',
        classification: 'LAST COMPLETED',
        taskCode: 'T-1022',
        taskName: 'Test Suite Execution for Milestone 1',
        ownerName: 'Amal Ramesh',
        role: 'QA',
        ownerRole: 'QA',
        taskType: 'Testing',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: '98.4% pass rate; 2 minor visual defects reported to Bedasur.',
        plannedStart: '05 Aug 2024',
        plannedEnd: '14 Aug 2024',
        actualLine1: '05 Aug → 13',
        actualLine2: 'Aug',
        varianceBadge: {
          label: '1 day early',
          type: 'success',
          icon: '⚡',
        },
        status: 'Completed',
        progressPct: 100,
        globalTab: 'Completed',
      },
      {
        id: 'fms-6',
        classification: 'BLOCKED',
        taskCode: 'T-1026',
        taskName: 'Audit Logging Service & Compliance Export',
        ownerName: 'Amal Ramesh',
        role: 'QA',
        ownerRole: 'QA & Automation',
        taskType: 'Testing',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Blocker: Waiting on S3 bucket ACL policy update from DevSecOps.',
        remarksPrefix: 'Blocker:',
        remarksPrefixColor: '#DC2626',
        plannedStart: '18 Aug 2024',
        plannedEnd: '26 Aug 2024',
        actualLine1: '20 Aug →',
        actualLine2: 'Running',
        varianceBadge: {
          label: '+2d start lag',
          type: 'warning',
          icon: '⚡',
        },
        status: 'Blocked',
        progressPct: 20,
        globalTab: 'On Hold',
        isDelayed: true,
        isBlocker: true,
      },
      {
        id: 'fms-7',
        classification: 'NOT STARTED',
        taskName: 'Real-time WebSocket Notification Gateway',
        ownerName: 'Bedasur V.',
        ownerRole: 'Frontend Lead',
        riskCategory: 'NA',
        remarks: 'Scheduled to kick off immediately following milestone 1 sign-off.',
        plannedStart: '25 Aug 2024',
        plannedEnd: '05 Sep 2024',
        actualLine1: '—',
        actualLine2: 'Not Started',
        varianceBadge: {
          label: 'On track',
          type: 'neutral',
        },
        status: 'Not Started',
        progressPct: 0,
        globalTab: 'All',
      },
    ],
  },
  {
    id: 'PRJ-9022',
    name: 'PMS',
    projectCode: 'ID #PRJ-9021',
    statusTag: 'On Schedule',
    lead: 'Kusum',
    teamMembersCount: 4,
    timeline: '01 Aug 2024 → 30 Sep 2024',
    activeTasksCount: 5,
    milestoneCompletion: 78,
    tabCounts: {
      all: 103,
      inProgress: 11,
      lastCompleted: 19,
      totalCompleted: 45,
      notStarted: 28,
      blockers: 4,
      delayed: 3,
      dueToday: 8,
    },
    tasks: [
      {
        id: 'mqt-1',
        classification: 'IN-PROGRESS',
        taskCode: 'T-1024',
        taskName: 'RBAC Permission Matrix & API Endpoints',
        ownerName: 'Navithkumar V.',
        role: 'Fullstack',
        ownerRole: 'Fullstack',
        taskType: 'Development',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Awaiting: InfoSec team formal sign-off for OAuth scoping.',
        remarksPrefix: 'Awaiting:',
        remarksPrefixColor: '#D97706',
        plannedStart: '18 Aug 2024',
        plannedEnd: '22 Aug 2024',
        actualLine1: '11 Aug →',
        actualLine2: 'Running',
        varianceBadge: {
          label: 'On track',
          type: 'neutral',
        },
        status: 'In Progress',
        progressPct: 65,
        globalTab: 'In Progress',
      },
      {
        id: 'mqt-2',
        classification: 'IN-PROGRESS',
        taskCode: 'T-1025',
        taskName: '1366px Responsive Grid & Task Matrix UI',
        ownerName: 'Bedasur V.',
        role: 'UI/UX',
        ownerRole: 'UI/UX',
        taskType: 'Design',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Blocker: Horizontal scroll glitch on nested tables in Firefox ESR; patch in testing.',
        remarksPrefix: 'Blocker:',
        remarksPrefixColor: '#DC2626',
        plannedStart: '13 Aug 2024',
        plannedEnd: '24 Aug 2024',
        actualLine1: '14 Aug →',
        actualLine2: 'Running',
        varianceBadge: {
          label: '+1d start lag',
          type: 'warning',
          icon: '⚡',
        },
        status: 'In Progress',
        progressPct: 48,
        globalTab: 'In Progress',
        isDelayed: true,
        isBlocker: true,
      },
      {
        id: 'mqt-3',
        classification: 'LAST COMPLETED',
        taskCode: 'T-1020',
        taskName: 'Core Authentication & JWT Middleware',
        ownerName: 'Navithkumar V.',
        role: 'Backend',
        ownerRole: 'Backend',
        taskType: 'Architecture',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Merged to staging branch. Code reviewed by Yusuf.',
        plannedStart: '01 Aug 2024',
        plannedEnd: '06 Aug 2024',
        actualLine1: '01 Aug → 07',
        actualLine2: 'Aug',
        varianceBadge: {
          label: '1 day early',
          type: 'success',
          icon: '⚡',
        },
        status: 'Completed',
        progressPct: 100,
        globalTab: 'Completed',
      },
      {
        id: 'mqt-4',
        classification: 'LAST COMPLETED',
        taskCode: 'T-1021',
        taskName: 'PostgreSQL Schema Partitioning & Indexing',
        ownerName: 'Yusuf Mohammed',
        role: 'Data Eng',
        ownerRole: 'Data Eng',
        taskType: 'Development',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: 'Query latency reduced by 40% on historical reports.',
        plannedStart: '02 Aug 2024',
        plannedEnd: '10 Aug 2024',
        actualLine1: '02 Aug → 09',
        actualLine2: 'Aug',
        varianceBadge: {
          label: '1 day early',
          type: 'success',
          icon: '⚡',
        },
        status: 'Completed',
        progressPct: 100,
        globalTab: 'Completed',
      },
      {
        id: 'mqt-5',
        classification: 'LAST COMPLETED',
        taskCode: 'T-1022',
        taskName: 'Test Suite Execution for Milestone 1',
        ownerName: 'Amal Ramesh',
        role: 'QA',
        ownerRole: 'QA',
        taskType: 'Testing',
        unit: '1 Unit',
        riskCategory: 'NA',
        remarks: '98.4% pass rate; 2 minor visual defects reported to Bedasur.',
        plannedStart: '05 Aug 2024',
        plannedEnd: '14 Aug 2024',
        actualLine1: '05 Aug → 13',
        actualLine2: 'Aug',
        varianceBadge: {
          label: '1 day early',
          type: 'success',
          icon: '⚡',
        },
        status: 'Completed',
        progressPct: 100,
        globalTab: 'Completed',
      },
      {
        id: 'mqt-6',
        classification: 'BLOCKED',
        taskName: 'Automated Billing Reconciliation Service',
        ownerName: 'Amal Ramesh',
        ownerRole: 'QA & Automation',
        riskCategory: 'NA',
        remarks: 'Blocker: Awaiting mock sandbox credentials from payment vendor.',
        remarksPrefix: 'Blocker:',
        remarksPrefixColor: '#DC2626',
        plannedStart: '15 Aug 2024',
        plannedEnd: '28 Aug 2024',
        actualLine1: '18 Aug →',
        actualLine2: 'Running',
        varianceBadge: {
          label: '+3d start lag',
          type: 'warning',
          icon: '⚡',
        },
        status: 'Blocked',
        progressPct: 25,
        globalTab: 'On Hold',
        isDelayed: true,
        isBlocker: true,
      },
    ],
  },
];
